#pragma once
#include <time.h>
#include <math.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <algorithm>
#include <assert.h>
#include <omp.h>
